DWAPlannerROS:
# DWA局部路径规划算法
# Robot Configuration Parameters 机器人配置参数
  max_vel_x: 0.22 # x方向最大线速度m/s
  min_vel_x: -0.22 # x方向最小线速度m/s

  max_vel_y: 0.0 # y方向最大线速度m/s
  min_vel_y: 0.0 # y方向最小线速度m/s

# The velocity when robot is moving in a straight line
# 机器人直线运动时的速度
  max_trans_vel:  0.22 #  机器人最大平移速度m/s
  min_trans_vel:  0.11 # 机器人最小平移速度m/s

  max_rot_vel: 2.75 # 机器人最大旋转角速度rad/s
  min_rot_vel: 1.37 # 机器人最小旋转角速度rad/s

  acc_lim_x: 2.5 # x方向最大加速度m/s^2
  acc_lim_y: 0.0 # y方向最大加速度m/s^2
  acc_lim_theta: 3.2 # 最大旋转角速度rad/s^2

# Goal Tolerance Parametes
# 目标误差参数
  xy_goal_tolerance: 0.05 # x,y平面内与目标位置的距离允许误差
  yaw_goal_tolerance: 0.17 # 与目标位置的角度允许误差
  latch_xy_goal_tolerance: false # 设置为true时，当到达距离允许误差后，设置一个锁，机器人只在原地旋转调整角度，调整过程中，xy超出误差范围也不会进行调整

# Forward Simulation Parameters
# 前向模拟参数
  sim_time: 1.5 # 预测未来1.5s的轨迹
  vx_samples: 20 # x方向速度空间的采样点数
  vy_samples: 0 # y方向速度空间的采样点数
  vth_samples: 40 # 旋转方向速度空间的采样点数
  controller_frequency: 10.0 # 向机器人底座发送速度命令的周期

# Trajectory Scoring Parameters
# 轨迹评分参数
  path_distance_bias: 32.0 # 机器人与给定路径接近程度的权重
  goal_distance_bias: 20.0 # 机器人与局部目标点的接近程度的权重
  occdist_scale: 0.02 # 机器人躲避障碍物的程度
  forward_point_distance: 0.325 # 将当前点与局部的global path终点连线，并延长0.325的距离作为附加评分点
  stop_time_buffer: 0.2 # 为防止碰撞，机器人必须提前stop_time_buffer时间停止
  scaling_speed: 0.25 # 启动机器人底盘的速度;当前机器人平移速度<scaling_speed，缩放因子为1.0,否则缩放因子为(vmag - scaling_speed) / (max_trans_vel - scaling_speed) * max_scaling_factor + 1.0，该缩放因子会被用于计算轨迹中各个点的footprintCost
  max_scaling_factor: 0.2 # 最大缩放因子

# Oscillation Prevention Parameters
# 震荡抑制参数
  oscillation_reset_dist: 0.05 # 机器人运动多远距离才会重置震荡标志

# Debugging
# 调试参数
  publish_traj_pc : true # 将规划的轨迹在RVIZ上进行可视化
  publish_cost_grid_pc: true # 将代价值进行可视化显示//
